// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAqYMeYAo8cgMJAAsTHmlbMi4P4I6KaQRc",
      authDomain: "onarproject-e5594.firebaseapp.com",
      projectId: "onarproject-e5594",
      storageBucket: "onarproject-e5594.appspot.com",
      messagingSenderId: "2501809769",
      appId: "1:2501809769:web:630181d2fca48c8cb7b4f8",
      measurementId: "G-8ME8RP8S01");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8uFGBxFn0MJhKtB4nE6RV0f-6y8vW3UA',
    appId: '1:2501809769:android:193c6b2a29669a23b7b4f8',
    messagingSenderId: '2501809769',
    projectId: 'onarproject-e5594',
    databaseURL: '',
    storageBucket: '',
  );
}
